export const quizData = [
    {
      id: 1,
      titleimage:"/images/title-test.png",
      name: "100m",
      question: "What is the capital of France?",
      options: ["Paris", "London", "Berlin", "Rome"],
      correctAnswer: "Paris",
      image: "/images/diabetes.jpg",
    },
    {
      id: 2,
      name: "100m",
      titleimage:"/images/title-test.png",
      question: "Which planet is known as the Red Planet?",
      options: ["Earth", "Mars", "Jupiter", "Saturn"],
      correctAnswer: "Mars",
      image: "/images/diabetes.jpg",
    },
    {
        id: 3,
        name: "100m",
        titleimage:"/images/title-test.png",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 4,
        name: "100m",
        titleimage:"/images/title-test.png",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 5,
        name: "100m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 6,
        name: "100m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 7,
        name: "100m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 8,
        name: "100m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 9,
        name: "100m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 10,
        name: "200m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 11,
        name: "200m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 12,
        name: "200m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 13,
        name: "200m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 14,
        name: "200m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 15,
        name: "200m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 16,
        name: "200m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 17,
        name: "200m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 18,
        name: "200m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 19,
        name: "300m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 20,
        name: "300m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 21,
        name: "300m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 22,
        name: "300m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 23,
        name: "300m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 24,
        name: "300m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 25,
        name: "300m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 26,
        name: "300m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 27,
        name: "300m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 28,
        name: "400m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 29,
        name: "400m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 30,
        name: "400m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 31,
        name: "400m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 32,
        name: "400m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 33,
        name: "400m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 34,
        name: "400m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 35,
        name: "400m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 36,
        name: "400m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 37,
        name: "500m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 38,
        name: "500m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 39,
        name: "500m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 40,
        name: "500m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 41,
        name: "500m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 42,
        name: "500m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 43,
        name: "500m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 44,
        name: "500m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 45,
        name: "500m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 46,
        name: "600m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 47,
        name: "600m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 48,
        name: "600m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 49,
        name: "600m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 50,
        name: "600m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 51,
        name: "600m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 53,
        name: "600m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 54,
        name: "600m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
      {
        id: 55,
        name: "600m",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        image: "/images/diabetes.jpg",
      },
    // Add more questions here
  ];
  