export const Round2 = [
  {
    id: 1,
    level: 100,
    type: 4,
    question:"Describe to your Endocrinologist: the main side effects of SGLT-2Is. (One of you will be selected by the judging panel)",
    options: [],
    correctAnswer: "",
    image: "",
    audio:"",
    timer:180
  },
  {
    id: 2,
    level: 100,
    type: 4,
    question:"Mention to your cardiologist: the difference in prevalence between ASCVD and HF in T2D patients. (One of you will be selected by the judging panel)",
    options: [],
    correctAnswer: "",
    image: "",
    audio:"",
    timer:180
  },
  {
    id: 3,
    level: 100,
    type: 4,
    question:"Decribe to your pharmacist: the storage conditions of Ozempic pen. (One of you will be selected by the judging panel)",
    options: [],
    correctAnswer: "",
    image: "",
    audio:"",
    timer:180
  },
  {
    id: 4,
    level: 100,
    type: 4,
    question:"Describe to your Endocrinologist: 3 benefits of Ozempic vs Mounjaro. (One of you will be selected by the judging panel)",
    options: [],
    correctAnswer: "",
    image: "",
    audio:"",
    timer:180
  },
  {
    id: 5,
    level: 100,
    type: 4,
    question:"Mention to your GP how to aleviate nausea due to GLP-1 RA. (One of you will be selected by the judging panel)",
    options: [],
    correctAnswer: "",
    image: "",
    audio:"",
    timer:180
  },
  {
    id: 6,
    level: 100,
    type: 4,
    question:"Rybelsus has no CV benefits. Respond to this claim by your IM doctor. (One of you will be selected by the judging panel)",
    options: [],
    correctAnswer: "",
    image: "",
    audio:"",
    timer:180
  },
  {
    id: 7,
    level: 200,
    type: 2,
    question:"Rybelsus launch year in Kuwait.",
    options: [],
    correctAnswer: "2021",
    image: "",
    audio:"",
    timer:60
  },
  {
    id: 8,
    level: 200,
    type: 2,
    question:"ozempic launch year in Oman.",
    options: [],
    correctAnswer: "2025",
    image: "",
    audio:"",
    timer:60
  },
  {
    id: 9,
    level: 200,
    type: 4,
    question:"Mention to your GP: the benefits of Rybelsus vs. Januvia in 3 points and use one of PIONEER trials as reference. (One of you will be selected by the judging panel)",
    options: [],
    correctAnswer: "",
    image: "",
    audio:"",
    timer:180
  },
  {
    id: 10,
    level: 200,
    type: 4,
    question:"An IM doctor asks about the use of Rybelsus with Insulin: use relevant PIONEER trial. (One of you will be selected by the judging panel)",
    options: [],
    correctAnswer: "",
    image: "",
    audio:"",
    timer:180
  },
  {
    id: 11,
    level: 200,
    type: 4,
    question:"How are renal and CV disease linked to T2DM? Describe to your GP. (One of you will be selected by the judging panel)",
    options: [],
    correctAnswer: "",
    image: "",
    audio:"",
    timer:180
  },
  {
    id: 12,
    level: 200,
    type: 4,
    question:"Compare between Rybelsus and Victoza using one of PIONEER trials (One of you will be selected by the judging panel)",
    options: [],
    correctAnswer: "",
    image: "",
    audio:"",
    timer:180
  },
  {
    id: 13,
    level: 300,
    type: 2,
    question:"one opportunity and one challenge for KOC for GLP-1",
    options: [],
    correctAnswer: "opportunity: GPs, challenge: mounjaro + budget restrictions and fear of abuse",
    image: "",
    audio:"",
    timer:60
  },
  {
    id: 14,
    level: 300,
    type: 2,
    question:"OZEMPIC is now available in Bahrain MOH. T or F",
    options: [],
    correctAnswer: "F",
    image: "",
    audio:"",
    timer:60
  },
  {
    id: 15,
    level: 300,
    type: 2,
    question:"Kuwait MOAD Value MS% for Rybelsus November 2024.",
    options: [],
    correctAnswer: "28%",
    image: "",
    audio:"",
    timer:60
  },
  {
    id: 16,
    level: 300,
    type: 2,
    question:"Kuwait GLP-1 Value MS% of Ozempic & Mounjaro November 2024.",
    options: [],
    correctAnswer: "27.7% and 72%",
    image: "",
    audio:"",
    timer:60
  },
  {
    id: 17,
    level: 300,
    type: 4,
    question:"Discuss PIONEER REAL. (One of you will be selected by the judging panel)",
    options: [],
    correctAnswer: "",
    image: "",
    audio:"",
    timer:180
  },
  {
    id: 18,
    level: 300,
    type: 4,
    question:"How can Rybelsus be administered for patients on Thyroid medication? (One of you will be selected by the judging panel)",
    options: [],
    correctAnswer: "",
    image: "",
    audio:"",
    timer:180
  },
];
